## 데이터 인코딩
### Label encoding // One-hot encoding

### 레이블 인코딩

In [1]:
from sklearn.preprocessing import LabelEncoder

In [8]:
fruits = ['사과','바나나','바나나','사과',
          '참외','귤','사과','참외','바나나','바나나']

In [9]:
# 레이블 인코더 생성
label_encoder = LabelEncoder()

In [10]:
# 적용
fruits_label_encoded = label_encoder.fit_transform(fruits)
print('적용 후 데이터: ',fruits_label_encoded)
print(fruits)

적용 후 데이터:  [2 1 1 2 3 0 2 3 1 1]
['사과', '바나나', '바나나', '사과', '참외', '귤', '사과', '참외', '바나나', '바나나']


### 원-핫 인코딩

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
# 원-핫 인코더 생성
onehot_encoder = OneHotEncoder()
# 적용
fruits_onehot_encoded = onehot_encoder.fit_transform(fruits_label_encoded.reshape(-1,1))

In [13]:
print('원-핫 인코딩 적용 데이터 :\n',fruits_onehot_encoded.toarray())

원-핫 인코딩 적용 데이터 :
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


### 판다스 get_dummies

In [14]:
import pandas as pd

In [15]:
pd.get_dummies(fruits)

귤  바나나  사과  참외
0  0    0   1   0
1  0    1   0   0
2  0    1   0   0
3  0    0   1   0
4  0    0   0   1
5  1    0   0   0
6  0    0   1   0
7  0    0   0   1
8  0    1   0   0
9  0    1   0   0