In [1]:
import pandas as pd

train = pd.read_csv('train.csv', index_col='id')
test = pd.read_csv('test.csv', index_col='id')
submission = pd.read_csv('sample_submission.csv', index_col='id')

In [19]:
train.head()

bin_0  bin_1  bin_2 bin_3 bin_4  nom_0      nom_1    nom_2    nom_3  \
id                                                                        
0       0      0      0     T     Y  Green   Triangle    Snake  Finland   
1       0      1      0     T     Y  Green  Trapezoid  Hamster   Russia   
2       0      0      0     F     Y   Blue  Trapezoid     Lion   Russia   
3       0      1      0     F     Y    Red  Trapezoid    Snake   Canada   
4       0      0      0     F     N    Red  Trapezoid     Lion   Canada   

       nom_4  ...      nom_9 ord_0        ord_1        ord_2 ord_3  ord_4  \
id            ...                                                           
0    Bassoon  ...  2f4cb3d51     2  Grandmaster         Cold     h      D   
1      Piano  ...  f83c56c21     1  Grandmaster          Hot     a      A   
2   Theremin  ...  ae6800dd0     1       Expert     Lava Hot     h      R   
3       Oboe  ...  8270f0d71     1  Grandmaster  Boiling Hot     i      D   
4       Oboe  ...  b164b72a7     1  Grandmaster     Freezing     a      R   

   ord_5 day month target  
id                         
0     kr   2     2      0  
1     bF   7     8      0  
2     Jc   7     2      0  
3     kW   2     1      1  
4     qP   7     8      0  

[5 rows x 24 columns]

In [20]:
test.head()

bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2    nom_3  \
id                                                                           
300000      0      0      1     T     Y  Blue   Triangle  Axolotl  Finland   
300001      0      0      0     T     N   Red     Square     Lion   Canada   
300002      1      0      1     F     Y  Blue     Square      Dog    China   
300003      0      0      1     T     Y   Red       Star      Cat    China   
300004      0      1      1     F     N   Red  Trapezoid      Dog    China   

        nom_4  ...      nom_8      nom_9 ord_0        ord_1     ord_2  ord_3  \
id             ...                                                             
300000  Piano  ...  9d117320c  3c49b42b8     2       Novice      Warm      j   
300001  Piano  ...  46ae3059c  285771075     1       Master  Lava Hot      l   
300002  Piano  ...  b759e21f0  6f323c53f     2       Expert  Freezing      a   
300003  Piano  ...  0b6ec68ff  b5de3dcc4     1  Contributor  Lava Hot      b   
300004  Piano  ...  f91f3b1ee  967cfa9c9     3  Grandmaster  Lava Hot      l   

       ord_4 ord_5 day month  
id                            
300000     P    be   5    11  
300001     A    RP   7     5  
300002     G    tP   1    12  
300003     Q    ke   2     3  
300004     W    qK   4    11  

[5 rows x 23 columns]

In [2]:
submission.head()

target
id            
300000     0.5
300001     0.5
300002     0.5
300003     0.5
300004     0.5

### 피처 엔지니어링

In [3]:
# 데이터 합치기
# 훈련 데이터와 테스트 데이터 합치기
all_data = pd.concat([train, test])
# 타깃값 제거
all_data = all_data.drop('target', axis=1)
all_data

bin_0  bin_1  bin_2 bin_3 bin_4  nom_0      nom_1    nom_2  \
id                                                                   
0           0      0      0     T     Y  Green   Triangle    Snake   
1           0      1      0     T     Y  Green  Trapezoid  Hamster   
2           0      0      0     F     Y   Blue  Trapezoid     Lion   
3           0      1      0     F     Y    Red  Trapezoid    Snake   
4           0      0      0     F     N    Red  Trapezoid     Lion   
...       ...    ...    ...   ...   ...    ...        ...      ...   
499995      0      0      0     F     N  Green     Square     Lion   
499996      1      0      0     F     Y  Green  Trapezoid     Lion   
499997      0      1      1     T     Y  Green  Trapezoid     Lion   
499998      1      0      0     T     Y   Blue       Star  Hamster   
499999      0      0      0     T     Y  Green       Star     Lion   

             nom_3     nom_4  ...      nom_8      nom_9 ord_0        ord_1  \
id                            ...                                            
0          Finland   Bassoon  ...  c389000ab  2f4cb3d51     2  Grandmaster   
1           Russia     Piano  ...  4cd920251  f83c56c21     1  Grandmaster   
2           Russia  Theremin  ...  de9c9f684  ae6800dd0     1       Expert   
3           Canada      Oboe  ...  4ade6ab69  8270f0d71     1  Grandmaster   
4           Canada      Oboe  ...  cb43ab175  b164b72a7     1  Grandmaster   
...            ...       ...  ...        ...        ...   ...          ...   
499995      Canada  Theremin  ...  9e4b23160  acc31291f     1       Novice   
499996       China     Piano  ...  cfbd87ed0  eae3446d0     1  Contributor   
499997      Canada      Oboe  ...  1108bcd6c  33dd3cf4b     1       Novice   
499998  Costa Rica   Bassoon  ...  606ac930b  d4cf587dd     2  Grandmaster   
499999       India     Piano  ...  4ea576eb6  2d610f52c     2       Novice   

              ord_2  ord_3 ord_4 ord_5 day month  
id                                                
0              Cold      h     D    kr   2     2  
1               Hot      a     A    bF   7     8  
2          Lava Hot      h     R    Jc   7     2  
3       Boiling Hot      i     D    kW   2     1  
4          Freezing      a     R    qP   7     8  
...             ...    ...   ...   ...  ..   ...  
499995     Lava Hot      j     A    Gb   1     3  
499996     Lava Hot      f     S    Ed   2     2  
499997  Boiling Hot      g     V    TR   3     1  
499998  Boiling Hot      g     X    Ye   2     1  
499999     Freezing      l     J    ex   2     2  

[500000 rows x 23 columns]

## 원-핫 인코딩

In [4]:
from sklearn.preprocessing import OneHotEncoder
# 원-핫 인코더 생성
encoder = OneHotEncoder()
# 원-핫 인코딩 적용
all_data_encoded = encoder.fit_transform(all_data)

### 데이터 나누기

In [5]:
# 훈련 데이터 개수
num_train = len(train)
# 훈련 / 테스트 데이터 나누기
X_train = all_data_encoded[:num_train] # 0 ~ num_train -> 1행
X_test = all_data_encoded[num_train:] # num_train ~ 마지막 행

y= train['target']

In [6]:
num_train

300000

In [7]:
all_data_encoded

<500000x16552 sparse matrix of type '<class 'numpy.float64'>'
	with 11500000 stored elements in Compressed Sparse Row format>

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
# 훈련 데이터, 검증 데이터 분리
X_train, X_valid, y_train, y_valid=train_test_split(X_train,y,
                                                   test_size=0.1,
                                                   stratify=y,
                                                   random_state=10)

## 모델 훈련

In [10]:
from sklearn.linear_model import LogisticRegression
# 모델 생성
logistic_model = LogisticRegression(max_iter=1000, random_state=42)
# 모델 훈련
logistic_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

## 모델 성능 검증

In [11]:
logistic_model.predict_proba(X_valid)

array([[0.23263496, 0.76736504],
       [0.91416934, 0.08583066],
       [0.83009532, 0.16990468],
       ...,
       [0.24855122, 0.75144878],
       [0.4942606 , 0.5057394 ],
       [0.95661047, 0.04338953]])

In [12]:
logistic_model.predict(X_valid)

array([1, 0, 0, ..., 1, 1, 0])

In [13]:
# 검증 데이터를 활용한 타깃 예측
y_valid_preds = logistic_model.predict_proba(X_valid)[:,1]

In [14]:
y_valid_preds

array([0.76736504, 0.08583066, 0.16990468, ..., 0.75144878, 0.5057394 ,
       0.04338953])

In [15]:
# ROC AUC 점수 계산 함수
from sklearn.metrics import roc_auc_score

# 검증 데이터 ROC AUC
roc_auc = roc_auc_score(y_valid, y_valid_preds)
print(f'검증 데이터 ROC AUC: {roc_auc:.4f}')

검증 데이터 ROC AUC: 0.7965


# 예측 및 결과 제출

In [16]:
# 타깃값 1일 확률 예측
y_preds = logistic_model.predict_proba(X_test)[:,1]

In [17]:
# 제출 파일 생성
submission['target']= y_preds

In [18]:
submission

target
id              
300000  0.308398
300001  0.699128
300002  0.067937
300003  0.444877
300004  0.893113
...          ...
499995  0.311692
499996  0.142340
499997  0.405967
499998  0.491875
499999  0.186119

[200000 rows x 1 columns]